
version: "3.9"

services:

    backend-service:

        # build: ./backend
        image: avinash3003/tasktracker-backend:1.0
        container_name: backend-container
        ports:
         - "8000:8000"
        
        volumes:
         - db_data:/backend
        restart: unless-stopped
        networks:
         - tasktracker-network


    frontend-service: 
        # build: ./frontend
        image: avinash3003/tasktracker-frontend:1.0
        container_name: frontend-container
        ports:
         - "5173:5173"
        environment:
         - VITE_API_URL=http://localhost:8000
        depends_on:
         - backend-service
        networks:
         - tasktracker-network
        restart: unless-stopped

volumes:
    db_data: 

networks:
    tasktracker-network:
        driver: bridge
